---
- name: include vars
  hosts: all
  tasks:
    - name: include vars
      include_vars:
        dir: "settings/{{ charjabox_settings_path }}"
  tags: always

- name: general setup
  hosts: all
  become: true
  tags: general
  roles:
    - charjabox_general

- name: smb
  hosts: all
  become: true
  tags: smb
  roles:
    - role: bertvv.samba
      when: smb_enabled
    - role: smb
      when: smb_enabled

- name: docker
  hosts: all
  become: true
  vars:
    - docker_install_compose: true
    - docker_compose_path: /usr/bin/docker-compose
  roles:
    - role: geerlingguy.docker

- name: nginx
  hosts: all
  become: true
  roles:
    - role: nginx
      when: nginx_enabled

- name: portainer
  hosts: all
  become: true
  tags: portainer
  roles:
    - role: portainer
      when: portainer_enabled

- name: plex
  hosts: all
  become: true
  tags: plex
  roles:
    - role: plex
      when: plex_enabled

- name: jellyfin
  hosts: all
  become: true
  tags: jellyfin
  roles:
    - role: jellyfin
      when: jellyfin_enabled

- name: heimdall
  hosts: all
  become: true
  tags: heimdall
  roles:
    - role: heimdall
      when: heimdall_enabled

- name: bind
  hosts: all
  become: true
  tags: bind
  roles:
    - role: bind
      when: bind_enabled

- name: firefly
  hosts: all
  become: true
  tags: firefly
  roles:
    - role: firefly
      when: firefly_enabled

- name: lancache
  hosts: all
  become: true
  tags: lancache
  roles:
    - role: lancache
      when: lancache_enabled

- name: dokuwiki
  hosts: all
  become: true
  tags: dokuwiki
  roles:
    - role: dokuwiki
      when: dokuwiki_enabled

- name: timemachine
  hosts: all
  become: true
  tags: timemachine
  roles:
    - role: timemachine
      when: timemachine_enabled

- name: gitea
  hosts: all
  become: true
  tags: gitea
  roles:
    - role: gitea
      when: gitea_enabled
