---
- name: general setup
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
  tags: general
  roles:
    - charjabox_general

- name: smb
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/smb.yml"
  tags: smb
  roles:
    - role: bertvv.samba
      when: smb_enabled
    - role: smb
      when: smb_enabled

- name: docker
  hosts: all
  become: true
  vars:
    - docker_install_compose: true
    - docker_compose_path: /usr/bin/docker-compose
  roles:
    - role: geerlingguy.docker

- name: nginx
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/nginx.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
  roles:
    - role: nginx
      when: nginx_enabled

- name: portainer
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/portainer.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
  tags: portainer
  roles:
    - role: portainer
      when: portainer_enabled

- name: plex
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/plex.yml"
  tags: plex
  roles:
    - role: plex
      when: plex_enabled

- name: jellyfin
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/jellyfin.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
  tags: jellyfin
  roles:
    - role: jellyfin
      when: jellyfin_enabled

- name: heimdall
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/heimdall.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
  tags: heimdall
  roles:
    - role: heimdall
      when: heimdall_enabled

- name: bind
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/bind.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
  tags: bind
  roles:
    - role: bind
      when: bind_enabled

- name: firefly
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/firefly.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
  tags: firefly
  roles:
    - role: firefly
      when: firefly_enabled

- name: lancache
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/lancache.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
  tags: lancache
  roles:
    - role: lancache
      when: lancache_enabled

- name: dokuwiki
  hosts: all
  become: true
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/dokuwiki.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
  tags: dokuwiki
  roles:
    - role: dokuwiki
      when: dokuwiki_enabled

- name: timemachine
  hosts: all
  become: true
  tags: timemachine
  vars_files:
    - "settings/{{ charjabox_settings_path }}/charjabox_general.yml"
    - "settings/{{ charjabox_settings_path }}/charjabox_ports.yml"
    - "settings/{{ charjabox_settings_path }}/timemachine.yml"
  roles:
    - role: timemachine
      when: timemachine_enabled
