---
- name: install dependencies
  apt:
    name: "{{ charjabox_packages }}"
  tags:
    - dependencies

- name: set hostname
  hostname:
    name: "{{ charjabox_hostname }}"

- name: configure timezone
  timezone:
    name: "{{ charjabox_timezone }}"

- name: create charjabox group
  group:
    name: charjabox
    state: present

- name: create charjabox user
  user:
    name: charjabox
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: charjabox
    shell: /usr/sbin/nologin

- name: create docker-compose directory
  file:
    path: "{{ docker_compose_dir }}"
    state: directory
